title: Henry Freed
author: ""
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "sunrise"

plugins:
  - jekyll-include-cache

url: "https://hbfreed.com"

footer:
  links:
    - label: "GitHub"
      icon:  "fab fa-fw fa-github"
      url:   "https://github.com/hbfreed"

    - label: "Twitter"
      icon:  "fab fa-fw fa-twitter"
      url:   "https://twitter.com/hbfreed"

    - label: "Email"
      icon:  "fas fa-fw fa-envelope"
      url:   "mailto:hbfreed@protonmail.com"

    - label: "Hugging Face"
      icon:  "fa-solid fa-face-smiling-hands"
      url:   "https://huggingface.co/hbfreed"

atom_feed:
  hide: true